### ISSUE TITLE
Query/not working?

### ISSUE THREAD

**Issue by gavinkillion69** [bmurray/cheatguessr#1]
Hey, I can't figure out how to get it to function, wondering if I'm misusing or misunderstanding the purpose of it.

Launched .exe, can't work out how to operate from there - whether I host my own CG, or join another via browser etc.

Any assistance or this no longer working?

**Comment by bmurray** [comment]
It should be a web page. I don't know what port it uses; probably 8080. It has been a while. You can read the code and figure some of that out tho.
